-- 02_sequences.sql
-- Create Sequences for Auto-increment IDs

CREATE SEQUENCE seq_users_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_customers_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_suppliers_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_products_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_orders_id START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE seq_order_items_id START WITH 1 INCREMENT BY 1 NOCACHE;
